name: Check updated_at for repo and issues
on:
  workflow_dispatch:
    inputs:
  issues:
    types: [opened, edited, deleted, transferred, pinned, unpinned, closed, reopened, assigned, unassigned, labeled, unlabeled, locked, unlocked, milestoned, demilestoned]
jobs:
  check-updated-at:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          echo UPDATED_AT: ${{ github.event.issue.updated_at }}
          echo CREATED_AT: ${{ github.event.issue.created_at }}
