name: Check updated_at for repo and issues
on:
  workflow_dispatch:
    inputs:
  issues:
    types: [opened, edited, deleted, transferred, pinned, unpinned, closed, reopened, assigned, unassigned, labeled, unlabeled, locked, unlocked, milestoned, demilestoned]
jobs:
  check-updated-at:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          echo UPDATED_AT: ${{ github.event.issue.updated_at }}
          echo CREATED_AT: ${{ github.event.issue.created_at }}
      - name: List all issue updated_at/created_at times
        uses: actions/github-script@0.4.0
        with:
          github-token: ${{github.token}}
          script: |
            let response = await github.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            let data = response['data'];
          
            data.forEach(function(issue){
              var id = issue['number'];
              console.log('issue id: ' + id)
            });
    
